#pragma once
/**
 * @file OBJLoader.h
 * @brief Simple Wavefront .OBJ mesh file loader.
 *
 * Supports:
 *   v  — vertex positions
 *   vt — texture coordinates
 *   vn — vertex normals
 *   f  — faces (triangles and quads, auto-triangulated)
 *
 * Face formats supported:
 *   f v1 v2 v3                     (position only)
 *   f v1/vt1 v2/vt2 v3/vt3        (position + texcoord)
 *   f v1/vt1/vn1 v2/vt2/vn2 ...   (position + texcoord + normal)
 *   f v1//vn1 v2//vn2 v3//vn3     (position + normal, no texcoord)
 *
 * Error handling:
 *   - Missing file: returns empty Mesh and logs an error.
 *   - Malformed face tokens: logged, face skipped (no throw, no silent garbage).
 *   - Incomplete vertex records: logged, vertex skipped.
 *   - Out-of-range face indices: logged, face skipped.
 *   - Parse errors are counted in ParseResult::error_count.
 *
 * For headless testing without an OpenGL context, use OBJParser.h directly
 * (parse_content / parse_stream) — it has no SDL or GL dependencies.
 */

#include "Mesh.h"
#include "OBJParser.h"
#include "../core/Logger.h"

#include <cmath>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace qe {
namespace renderer {

class OBJLoader {
public:
    // Re-export the parser types so existing callers using OBJLoader::RawMesh
    // still compile.
    using RawMesh     = OBJRawMesh;
    using ParseResult = OBJParseResult;

    // ── Public parse API (no GPU) ────────────────────────────────────────────

    /** Parse OBJ content from a string (no file I/O, no GPU upload). */
    static ParseResult parse_content(const std::string& content) {
        return OBJParser::parse_content(content);
    }

    /** Parse OBJ content from an already-open stream (no GPU upload). */
    static ParseResult parse_stream(std::istream& stream) {
        return OBJParser::parse_stream(stream);
    }

    // ── GPU load ─────────────────────────────────────────────────────────────

    /** Load an OBJ file and return a renderable Mesh. */
    static Mesh load(const std::string& path,
                     float r = 0.7f, float g = 0.7f, float b = 0.7f) {
        std::ifstream file(path);
        if (!file.is_open()) {
            QE_LOG_ERROR("OBJ") << "Failed to open: " << path << std::endl;
            return Mesh();
        }

        ParseResult result = OBJParser::parse_stream(file);

        if (result.error_count > 0) {
            QE_LOG_WARN("OBJ") << path << ": " << result.error_count
                               << " parse error(s) — " << result.error_message
                               << std::endl;
        }

        QE_LOG_INFO("OBJ") << "Loaded " << path << ": "
                  << result.mesh.positions.size() / 3 << " verts, "
                  << result.mesh.face_verts.size() / 3 << " tris" << std::endl;

        return build_mesh(result.mesh, r, g, b);
    }

    /** Write a simple OBJ file for a given set of vertices and faces. */
    static bool write_obj(const std::string& path,
                          const std::vector<Vertex>& vertices,
                          const std::vector<unsigned int>& indices) {
        std::ofstream file(path);
        if (!file.is_open()) return false;

        file << "# Generated by QuatEngine\n";
        for (const auto& v : vertices) {
            file << "v " << v.position[0] << " " << v.position[1]
                 << " " << v.position[2] << "\n";
        }
        for (const auto& v : vertices) {
            file << "vn " << v.normal[0] << " " << v.normal[1]
                 << " " << v.normal[2] << "\n";
        }
        for (const auto& v : vertices) {
            file << "vt " << v.uv[0] << " " << v.uv[1] << "\n";
        }
        for (size_t i = 0; i + 2 < indices.size(); i += 3) {
            // OBJ indices are 1-based
            file << "f "
                 << indices[i]+1 << "/" << indices[i]+1 << "/" << indices[i]+1 << " "
                 << indices[i+1]+1 << "/" << indices[i+1]+1 << "/" << indices[i+1]+1 << " "
                 << indices[i+2]+1 << "/" << indices[i+2]+1 << "/" << indices[i+2]+1 << "\n";
        }

        return true;
    }

private:
    /** Convert a single face vertex to a renderable Vertex. */
    static Vertex build_vertex(const OBJRawMesh& raw, const OBJRawMesh::FaceVertex& fv,
                                float r, float g, float b) {
        Vertex vert{};

        // Position
        if (fv.pos_idx >= 0 && fv.pos_idx * 3 + 2 < static_cast<int>(raw.positions.size())) {
            vert.position[0] = raw.positions[fv.pos_idx * 3 + 0];
            vert.position[1] = raw.positions[fv.pos_idx * 3 + 1];
            vert.position[2] = raw.positions[fv.pos_idx * 3 + 2];
        }

        // Normal
        if (fv.norm_idx >= 0 && fv.norm_idx * 3 + 2 < static_cast<int>(raw.normals.size())) {
            vert.normal[0] = raw.normals[fv.norm_idx * 3 + 0];
            vert.normal[1] = raw.normals[fv.norm_idx * 3 + 1];
            vert.normal[2] = raw.normals[fv.norm_idx * 3 + 2];
        } else {
            vert.normal[0] = 0; vert.normal[1] = 1; vert.normal[2] = 0;
        }

        // Texcoord
        if (fv.tex_idx >= 0 && fv.tex_idx * 2 + 1 < static_cast<int>(raw.texcoords.size())) {
            vert.uv[0] = raw.texcoords[fv.tex_idx * 2 + 0];
            vert.uv[1] = raw.texcoords[fv.tex_idx * 2 + 1];
        }

        // Color
        vert.color[0] = r;
        vert.color[1] = g;
        vert.color[2] = b;

        return vert;
    }

    static Mesh build_mesh(const OBJRawMesh& raw, float r, float g, float b) {
        Mesh mesh;
        std::vector<Vertex> vertices;
        std::vector<unsigned int> indices;

        for (size_t i = 0; i < raw.face_verts.size(); ++i) {
            vertices.push_back(build_vertex(raw, raw.face_verts[i], r, g, b));
            indices.push_back(static_cast<unsigned int>(i));
        }

        if (raw.normals.empty()) {
            compute_face_normals(vertices, indices);
        }

        mesh.upload(vertices, indices);
        return mesh;
    }

    static void compute_face_normals(std::vector<Vertex>& vertices,
                                      const std::vector<unsigned int>& indices) {
        for (size_t i = 0; i + 2 < indices.size(); i += 3) {
            Vertex& v0 = vertices[indices[i]];
            Vertex& v1 = vertices[indices[i + 1]];
            Vertex& v2 = vertices[indices[i + 2]];

            float e1x = v1.position[0] - v0.position[0];
            float e1y = v1.position[1] - v0.position[1];
            float e1z = v1.position[2] - v0.position[2];
            float e2x = v2.position[0] - v0.position[0];
            float e2y = v2.position[1] - v0.position[1];
            float e2z = v2.position[2] - v0.position[2];

            float nx = e1y * e2z - e1z * e2y;
            float ny = e1z * e2x - e1x * e2z;
            float nz = e1x * e2y - e1y * e2x;

            float len = std::sqrt(nx * nx + ny * ny + nz * nz);
            if (len > 1e-6f) {
                nx /= len; ny /= len; nz /= len;
            }

            v0.normal[0] = v1.normal[0] = v2.normal[0] = nx;
            v0.normal[1] = v1.normal[1] = v2.normal[1] = ny;
            v0.normal[2] = v1.normal[2] = v2.normal[2] = nz;
        }
    }
};

} // namespace renderer
} // namespace qe
