name: DCO
on:
  pull_request:
    branches: [main]
jobs:
  dco:
    runs-on: d-sorg-fleet
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: DCO Check
        uses: proaction/dco@v1
        with:
          setup_git: false
